# Generated by Django 5.2.9 on 2026-01-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_companyinfo_applicant_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="company/"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
    ]
