# Generated by Django 5.2.10 on 2026-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_jobapplication_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_experience",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profiles/default.jpg",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
